#image: docker:latest
image: maven:3-jdk-8

variables:
  DOCKER_DRIVER: overlay

stages:
  - gh-install
  - ors-build
  - deploy
  - ors-api-test

maven-gh-install:
  stage: gh-install
  script: 
    - mvn -f ./graphhopper/pom.xml install -B
  only: 
    - development

maven-ors-build:
  stage: ors-build
  script: 
    - mvn -f ./openrouteservice/pom.xml package -B
  only: 
    - development
