language: java

branches:
  only:
  - master
  - development
  - integrate-travis

stages:
  - compile
  - test

jobs:
  include:
    - stage: compile
      script:
        - cp ${TRAVIS_BUILD_DIR}/openrouteservice-api-tests/conf/app.config.test ${TRAVIS_BUILD_DIR}/openrouteservice/WebContent/WEB-INF/app.config
        - mvn -f ${TRAVIS_BUILD_DIR}/openrouteservice/pom.xml install -B
    - stage: test
      script:
        - nohup mvn -f ${TRAVIS_BUILD_DIR}/openrouteservice/pom.xml tomcat7:run & > ${TRAVIS_BUILD_DIR}/build_graphs.out&
        - sleep 5m
        - mvn -f ${TRAVIS_BUILD_DIR}/openrouteservice-api-tests/pom.xml test

notifications:
  webhooks: https://chat.gistools.geog.uni-heidelberg.de/hooks/fqX555ZPxYFdHeqhS/2kxt4rNATiJ9cB8pLmkSc2R3mrxnmJrEQZFd7JKqiPEGFnW9
