##### openrouteservice settings file #####
# This file contains parameters for openrouteservice.
# For a full list of possible parameters see https://giscience.github.io/openrouteservice/, below are some examples.

### uncomment the following line to turn on debug output
#logging.level.org.heigit: DEBUG

ors:
  ### uncomment the following lines to change CORS settings.
#  cors:
#    allowed_origins: "*"
#    allowed_headers: Content-Type, X-Requested-With, accept, Origin, Access-Control-Request-Method, Access-Control-Request-Headers, Authorization
#    preflight_max_age: 600

  engine:
    ### use the following line to enable mmap mode
#    graphs_data_access: MMAP

    ### use the following lines for development setup using test OSM file for Heidelberg
#    source_file: ./ors-api/src/test/files/heidelberg.osm.gz
#    elevation:
#      cache_path: ./ors-api/src/test/files/elevation
    ### instead of the following 3 lines:
    source_file: ./ors-core/data/osm_file.pbf
    elevation:
      cache_path: ./ors-core/data/elevation_cache

    profiles:
      car:
        enabled: true
      hgv:
        enabled: true