name: Build and publish the nightly Docker image
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  TEST_IMAGE_NAME: 'local/openrouteservice:test'
  PRODUCTION_IMAGE_NAME: 'openrouteservice/openrouteservice:nightly'
  BUILD_PLATFORMS: 'linux/amd64'


jobs:
  # This way the env variables are accessible in the individual jobs
  prepare_environment:
    name: Prepare the environment variables
    runs-on: ubuntu-latest
    outputs:
      test_image_name: ${{ env.TEST_IMAGE_NAME }}
      production_image_name: ${{ env.PRODUCTION_IMAGE_NAME }}
      build_platforms: ${{ env.BUILD_PLATFORMS }}
    steps:
      - run: |
          echo "Publish enironment variables"
  build_docker_and_test_war_deployment:
    name: Build and check the war deployment stage
    runs-on: ubuntu-latest
    needs:
      - prepare_environment
    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: ${{ needs.prepare_environment.outputs.test_image_name }}
          build-args: "--platform ${{ needs.prepare_environment.outputs.build_platforms }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Start container from image and wait for successful checks
        run: |
          docker run -it -d -p 8080:8080 ${{ needs.prepare_environment.outputs.test_image_name }}
          ./.github/utils/health_check.sh 127.0.0.1 8080 /ors/
          ./.github/utils/cors_check.sh 127.0.0.1 8082 /ors/v2/isochrones/geojson "https://example.com" 403 10
          ./.github/utils/cors_check.sh 127.0.0.1 8082 /ors/v2/isochrones/geojson "https://example.org" 200 10
  publish_docker:
    name: Publish the docker image to docker hub
    runs-on: ubuntu-latest
    needs:
      - prepare_environment
      - build_docker_and_test_war_deployment
    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
      - name: Login to DockerHub
        if: ${{ success() && github.ref == 'refs/heads/master' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Publish nightly
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ needs.prepare_environment.outputs.production_image_name }}
          build-args: "--platform ${{ needs.prepare_environment.outputs.build_platforms }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max