name: project_automation_labels

on:
  issues:
    types: [labeled]

jobs:
  handle_labels:
    runs-on: ubuntu-latest
    steps:
    - name: move bugs to priority
      uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.PROJECT_AUTOMATION }}"
        project-url: "https://github.com/GIScience/openrouteservice/projects/16"
        column-name: "Priority"
        label-name: ":bug: bug"
        columns-to-ignore: "Priority,Assigned,In progress,Review,Awaiting release,Last release"
